In [ ]:
# Answer for Exercise 1



In [15]:
# Answer for Exercise 2

import numpy as np

arr1 = np.array([[6,-9,1], [4,24,8]])
print(2*arr1)

arr2 = np.eye(2)
print(arr2.dot(arr1))

arr3 = np.array([[4,3],[3,2]])
arr4 = np.array([[-2,3],[3,-4]])
print(arr3*arr4)

[[ 12 -18   2]
 [  8  48  16]]
[[ 6. -9.  1.]
 [ 4. 24.  8.]]
[[-8  9]
 [ 9 -8]]


In [28]:
# Answer for Exerise 3

arr = np.array([[0, 1, 2, 3, 4, 5],[10, 11, 12, 13, 14, 15],[20, 21, 22, 23, 24, 25],[30, 31, 32, 33, 34, 35],[40, 41, 42, 43, 44, 45],[50, 51, 52, 53, 54, 55]])

print(arr[:,1])

print(arr[1,2:4])

print(arr[2:4,4:])

[ 1 11 21 31 41 51]
[12 13]
[[24 25]
 [34 35]]


In [ ]:
# Answer for Exercise 4

